# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1a472a3f3020b48e7ef1fff439ac97811a7344694a627d26da5405e85390859712ad92b551af4940ecc0fc57b6a9084e2cc0bec5e6c0e96b945489c0b0bdb3e6

test:
  secret_key_base: b87371600e77f5472bbd71e0dfd79f21bd275c558e326a0746e81f81b8691e697a46cf7e0658fc1454701301bb00a969cf1b83aa6ccd5708373778bff4e2e7fe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
